HCLOUD-2963_Add-semantic-relese-to-the-wave-nodes-catalog-blueprint_Darius-Weiberg
moovit-sp-gmbh/wave-nodes-catalog-blueprint pull request #6
Opened 2024-10-17 11:07 UTC by DariusWe

Add everything necessary to create changelogs for releases

2024-10-21 13:50 UTC, JorgePBrown requested changes
Additionally to my other comments, could you one more script which would append to the pre-push hook a check if there are changelog changes when there are node changes?

2024-10-21 13:50 UTC, JorgePBrown commented on changelog-howTo.txt
Can you change this to a Markdown file and put the JSON inside a code block?

2024-10-22 13:31 UTC, DariusWe commented on scripts/check-changelog.mjs
> +}
There is an extra ticket for that:
https://app.clickup.com/t/2570196/HCLOUD-3069

I could also do it here though.

2024-10-22 13:45 UTC, DariusWe commented
@JorgePBrown Regarding the pre-push hook: These will have no effect in templates. We would have to implement them as custom hooks in the repository and then change the hooksPath. This means that users of the template could not use their own hooks anymore (without changing the hooksPath again), and all contributors would be forced to use the same. Probably not that problematic, but seems not worth if for me for now. What do you think?

2024-10-23 09:52 UTC, DariusWe commented on scripts/check-changelog.mjs
> +}
I will do it, however personally i think my solution is sufficient. Why would we want to allow more formats? The users will just use the format that is defined in the example anyways, and i think from a users perspective a restricted format removes uncertainty about what is allowed and what not.

2024-10-23 10:03 UTC, DariusWe commented on scripts/check-changelog.mjs
> +}
Done!

2024-10-23 10:03 UTC, DariusWe commented on changelog-howTo.txt
Done!

2024-10-30 08:19 UTC, JorgePBrown approved these changes

2024-10-30 08:19 UTC, JorgePBrown commented
> @JorgePBrown Regarding the pre-push hook: These will have no effect in templates. We would have to implement them as custom hooks in the repository and then change the hooksPath. This means that users of the template could not use their own hooks anymore (without changing the hooksPath again), and all contributors would be forced to use the same. Probably not that problematic, but seems not worth if for me for now. What do you think?

Makes sense. Leave it out then

2024-10-30 14:34 UTC, merged